apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      micro: gateway
  template:
    metadata:
      labels:
        micro: gateway
    spec:
      containers:
        - name: gatewaydeployment
          image: vineetkala11/gateway
          ports:
            - containerPort: 8084
          env:
            - name: EUREKA_SERVER
              value: http://eureka-server-service:8761/eureka